services:
  app:
    build: .
    container_name: hyper_five
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - hyper_five
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: hyper_five_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hyper_five
      MYSQL_USER: hyper_five
      MYSQL_PASSWORD: secret
    networks:
      - hyper_five

networks:
  hyper_five:
    driver: bridge
